apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  LOADBALANCERPROVIDERHAPROXY_EVENTS_SUBSCRIBER_PREFIX: "{{ .Values.provider.events.topicPrefix }}"
  LOADBALANCERPROVIDERHAPROXY_EVENTS_SUBSCRIBER_URL: "{{ .Values.provider.events.connectionURL }}"
  LOADBALANCERPROVIDERHAPROXY_EVENTS_PUBLISHER_URL: "{{ .Values.provider.events.connectionURL }}"
  LOADBALANCERPROVIDERHAPROXY_EVENTS_PUBLISHER_PREFIX: "{{ .Values.provider.events.topicPrefix }}"
  LOADBALANCERPROVIDERHAPROXY_EVENTS_QUEUEGROUP: "{{ .Values.provider.events.queueGroup }}"
  LOADBALANCERPROVIDERHAPROXY_API_ENDPOINT: "{{ .Values.provider.api.endpoint }}"
  LOADBALANCERPROVIDERHAPROXY_IPBLOCK: "{{ .Values.provider.ipBlock }}"
  LOADBALANCERPROVIDERHAPROXY_OIDC_CLIENT_ISSUER: "{{ .Values.provider.api.oidc.client.issuer }}"
